apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nick-test
  namespace: argocd
spec:
  description: Project for the autodeploy‑nicktest app
  sourceRepos:
    - https://github.com/nickbernstein-ham/autodploy-nicktest.git
  destinations:
    - namespace: nick-test
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
#  namespaceResourceBlacklist:
#    - group: '*'
#      kind: '*'
